---

# Create a key pair
- ec2_key:
     name: cba-challenge-key
     #aws_access_key: "{{ my_aws_access_key }}"
     #aws_secret_key: "{{ my_aws_secret_key }}" 
     region: eu-west-2
     force: yes
  register: ec2_key_result

# Save the key pair
- copy: content="{{ ec2_key_result.key.private_key }}" dest="~/.ssh/cba-challenge-key.pem" mode=0600
  when: ec2_key_result.changed

